// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package schema

import (
	"testing"

	"github.com/crossplane-contrib/function-hcl/function-hcl-ls/internal/langhcl/schema"
	"github.com/hashicorp/hcl/v2"
	"github.com/hashicorp/hcl/v2/hclsyntax"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// generated by Claude to verify the code against spec.md in the function-hcl repo.

// TestTopLevelBlocks verifies that top-level blocks match the spec
func TestTopLevelBlocks(t *testing.T) {
	rootSchema := std[""]
	require.NotNil(t, rootSchema)

	expectedBlocks := []string{
		"resource",    // Create a resource (spec section)
		"resources",   // Create list of resources (spec section)
		"group",       // Groups of resources (spec section)
		"locals",      // Local variables (spec section)
		"composite",   // Write composite status/connection (spec section)
		"context",     // Write to context (spec section)
		"requirement", // Extra resources requirements (spec section)
		"function",    // User-defined functions (spec section)
	}

	for _, blockType := range expectedBlocks {
		assert.Contains(t, rootSchema.NestedBlocks, blockType,
			"Top level should support %s block per spec", blockType)
	}
}

// TestResourceBlockSchema verifies resource block schema per spec
func TestResourceBlockSchema(t *testing.T) {
	resourceSchema := std["resource"]
	require.NotNil(t, resourceSchema, "resource block should have schema")

	// Per spec: resource blocks should have body attribute
	assert.Contains(t, resourceSchema.Attributes, "body",
		"resource block should have 'body' attribute per spec")

	// Per spec: resource blocks support condition attribute
	assert.Contains(t, resourceSchema.Attributes, "condition",
		"resource block should support 'condition' attribute per spec")

	// Condition should be boolean and optional
	condAttr := resourceSchema.Attributes["condition"]
	assert.True(t, condAttr.IsOptional, "condition should be optional per spec")

	// Per spec: resource blocks can have nested blocks
	expectedNested := []string{"locals", "composite", "context", "ready"}
	for _, nested := range expectedNested {
		assert.Contains(t, resourceSchema.NestedBlocks, nested,
			"resource block should support %s nested block per spec", nested)
	}
}

// TestResourcesBlockSchema verifies resources (collection) block schema per spec
func TestResourcesBlockSchema(t *testing.T) {
	resourcesSchema := std["resources"]
	require.NotNil(t, resourcesSchema, "resources block should have schema")

	// Per spec: resources blocks must have for_each
	assert.Contains(t, resourcesSchema.Attributes, "for_each",
		"resources block must have 'for_each' attribute per spec")
	forEachAttr := resourcesSchema.Attributes["for_each"]
	assert.False(t, forEachAttr.IsOptional,
		"for_each should be required per spec")

	// Per spec: resources blocks should have optional name attribute
	assert.Contains(t, resourcesSchema.Attributes, "name",
		"resources block should have optional 'name' attribute per spec")
	nameAttr := resourcesSchema.Attributes["name"]
	assert.True(t, nameAttr.IsOptional,
		"name attribute should be optional per spec (defaults to ${self.basename}-${each.key})")

	// Per spec: resources blocks support condition
	assert.Contains(t, resourcesSchema.Attributes, "condition",
		"resources block should support 'condition' attribute per spec")

	// Per spec: resources must have template nested block
	assert.Contains(t, resourcesSchema.NestedBlocks, "template",
		"resources block must have 'template' nested block per spec")
}

// TestGroupBlockSchema verifies group block schema per spec
func TestGroupBlockSchema(t *testing.T) {
	groupSchema := std["group"]
	require.NotNil(t, groupSchema, "group block should have schema")

	// Per spec: group blocks support condition
	assert.Contains(t, groupSchema.Attributes, "condition",
		"group block should support 'condition' attribute per spec")

	// Per spec: group blocks can contain resources, resource, locals, composite, context, requirement
	expectedNested := []string{"resource", "resources", "group", "locals", "composite", "context", "requirement"}
	for _, nested := range expectedNested {
		assert.Contains(t, groupSchema.NestedBlocks, nested,
			"group block should support %s nested block per spec", nested)
	}
}

// TestCompositeBlockSchema verifies composite status/connection block schema per spec
func TestCompositeBlockSchema(t *testing.T) {
	compositeSchema := std["composite"]
	require.NotNil(t, compositeSchema, "composite block should have schema")

	// Per spec: composite blocks must have body attribute
	assert.Contains(t, compositeSchema.Attributes, "body",
		"composite block must have 'body' attribute per spec")
	bodyAttr := compositeSchema.Attributes["body"]
	assert.True(t, bodyAttr.IsRequired,
		"body attribute should be required per spec")

	// Per spec: composite blocks can have locals
	assert.Contains(t, compositeSchema.NestedBlocks, "locals",
		"composite block should support 'locals' nested block per spec")
}

// TestContextBlockSchema verifies context block schema per spec
func TestContextBlockSchema(t *testing.T) {
	contextSchema := std["context"]
	require.NotNil(t, contextSchema, "context block should have schema")

	// Per spec: context blocks must have key and value attributes
	assert.Contains(t, contextSchema.Attributes, "key",
		"context block must have 'key' attribute per spec")
	assert.Contains(t, contextSchema.Attributes, "value",
		"context block must have 'value' attribute per spec")

	keyAttr := contextSchema.Attributes["key"]
	valueAttr := contextSchema.Attributes["value"]

	assert.True(t, keyAttr.IsRequired, "key attribute should be required per spec")
	assert.True(t, valueAttr.IsRequired, "value attribute should be required per spec")

	// Per spec: context blocks can have locals
	assert.Contains(t, contextSchema.NestedBlocks, "locals",
		"context block should support 'locals' nested block per spec")
}

// TestRequirementBlockSchema verifies requirement block schema per spec
func TestRequirementBlockSchema(t *testing.T) {
	requirementSchema := std["requirement"]
	require.NotNil(t, requirementSchema, "requirement block should have schema")

	// Per spec: requirement blocks support condition
	assert.Contains(t, requirementSchema.Attributes, "condition",
		"requirement block should support 'condition' attribute per spec")

	// Per spec: requirement blocks must have select nested block
	assert.Contains(t, requirementSchema.NestedBlocks, "select",
		"requirement block must have 'select' nested block per spec")

	// Per spec: requirement blocks can have locals
	assert.Contains(t, requirementSchema.NestedBlocks, "locals",
		"requirement block should support 'locals' nested block per spec")
}

// TestSelectBlockSchema verifies select block schema per spec
func TestSelectBlockSchema(t *testing.T) {
	selectSchema := std["select"]
	require.NotNil(t, selectSchema, "select block should have schema")

	// Per spec: select blocks must have apiVersion and kind
	assert.Contains(t, selectSchema.Attributes, "apiVersion",
		"select block must have 'apiVersion' attribute per spec")
	assert.Contains(t, selectSchema.Attributes, "kind",
		"select block must have 'kind' attribute per spec")

	apiVersionAttr := selectSchema.Attributes["apiVersion"]
	kindAttr := selectSchema.Attributes["kind"]

	assert.True(t, apiVersionAttr.IsRequired, "apiVersion should be required per spec")
	assert.True(t, kindAttr.IsRequired, "kind should be required per spec")

	// Per spec: select blocks can have matchName or matchLabels (optional)
	assert.Contains(t, selectSchema.Attributes, "matchName",
		"select block should have 'matchName' attribute per spec")
	assert.Contains(t, selectSchema.Attributes, "matchLabels",
		"select block should have 'matchLabels' attribute per spec")

	matchNameAttr := selectSchema.Attributes["matchName"]
	matchLabelsAttr := selectSchema.Attributes["matchLabels"]

	assert.True(t, matchNameAttr.IsOptional, "matchName should be optional per spec")
	assert.True(t, matchLabelsAttr.IsOptional, "matchLabels should be optional per spec")

	// Verify correct descriptions (Bug #2 fix verification)
	assert.Contains(t, matchNameAttr.Description.Value(), "name",
		"matchName description should mention 'name'")
	assert.Contains(t, matchLabelsAttr.Description.Value(), "labels",
		"matchLabels description should mention 'labels'")
}

// TestFunctionBlockSchema verifies function definition block schema per spec
func TestFunctionBlockSchema(t *testing.T) {
	functionSchema := std["function"]
	require.NotNil(t, functionSchema, "function block should have schema")

	// Per spec: function blocks must have body attribute
	assert.Contains(t, functionSchema.Attributes, "body",
		"function block must have 'body' attribute per spec")
	bodyAttr := functionSchema.Attributes["body"]
	assert.True(t, bodyAttr.IsRequired,
		"body attribute should be required per spec")

	// Per spec: function blocks can have description
	assert.Contains(t, functionSchema.Attributes, "description",
		"function block should support optional 'description' attribute per spec")
	descAttr := functionSchema.Attributes["description"]
	assert.True(t, descAttr.IsOptional,
		"description attribute should be optional per spec")

	// Per spec: function blocks can have arg and locals nested blocks
	assert.Contains(t, functionSchema.NestedBlocks, "arg",
		"function block should support 'arg' nested block per spec")
	assert.Contains(t, functionSchema.NestedBlocks, "locals",
		"function block should support 'locals' nested block per spec")

	// Per spec: multiple arg blocks are allowed
	argBlock := functionSchema.NestedBlocks["arg"]
	assert.True(t, argBlock.AllowMultiple,
		"arg blocks should allow multiple instances per spec")
}

// TestArgBlockSchema verifies function argument block schema per spec
func TestArgBlockSchema(t *testing.T) {
	argSchema := std["arg"]
	require.NotNil(t, argSchema, "arg block should have schema")

	// Per spec: arg blocks can have description and default
	assert.Contains(t, argSchema.Attributes, "description",
		"arg block should support 'description' attribute per spec")
	assert.Contains(t, argSchema.Attributes, "default",
		"arg block should support 'default' attribute per spec")

	descAttr := argSchema.Attributes["description"]
	defaultAttr := argSchema.Attributes["default"]

	assert.True(t, descAttr.IsOptional, "description should be optional per spec")
	assert.True(t, defaultAttr.IsOptional, "default should be optional per spec")
}

// TestReadyBlockSchema verifies ready block is supported in resource/template
func TestReadyBlockSchema(t *testing.T) {
	// Per spec: ready blocks should exist in resource and template children
	resourceSchema := std["resource"]
	assert.Contains(t, resourceSchema.NestedBlocks, "ready",
		"resource block should support 'ready' nested block per spec")

	templateSchema := std["template"]
	assert.Contains(t, templateSchema.NestedBlocks, "ready",
		"template block should support 'ready' nested block per spec")

	// Per spec: ready block must have its own schema with value attribute
	readySchema := std["ready"]
	require.NotNil(t, readySchema, "ready block must have schema definition")

	// Per spec: ready block must have value attribute
	assert.Contains(t, readySchema.Attributes, "value",
		"ready block must have 'value' attribute per spec")

	valueAttr := readySchema.Attributes["value"]
	assert.True(t, valueAttr.IsRequired,
		"value attribute must be required per spec")

	// Value should be a string (READY_UNSPECIFIED, READY_TRUE, or READY_FALSE)
	assert.EqualValues(t, schema.String{}, valueAttr.Constraint,
		"value should be string per spec")
}

// TestTemplateBlockSchema verifies template block schema
func TestTemplateBlockSchema(t *testing.T) {
	templateSchema := std["template"]
	require.NotNil(t, templateSchema, "template block should have schema")

	// Per spec: template blocks behave like resource blocks
	// Should have same attributes and nested blocks as resource
	assert.Contains(t, templateSchema.Attributes, "body",
		"template block should have 'body' attribute like resource block per spec")
	assert.Contains(t, templateSchema.Attributes, "condition",
		"template block should support 'condition' like resource block per spec")

	// Should have same nested blocks
	expectedNested := []string{"locals", "composite", "context", "ready"}
	for _, nested := range expectedNested {
		assert.Contains(t, templateSchema.NestedBlocks, nested,
			"template block should support %s nested block like resource per spec", nested)
	}
}

// TestLocalsBlockSchema verifies locals block schema per spec
func TestLocalsBlockSchema(t *testing.T) {
	localsSchema := std["locals"]
	require.NotNil(t, localsSchema, "locals block should have schema")

	// Per spec: locals blocks can appear in many places
	blocksWithLocals := []string{
		"", "resource", "resources", "template", "group",
		"composite", "context", "requirement", "function",
	}

	for _, blockType := range blocksWithLocals {
		blockSchema := std[blockType]
		require.NotNil(t, blockSchema, "%s should have schema", blockType)

		if blockType == "locals" {
			// locals itself doesn't nest locals
			continue
		}

		assert.Contains(t, blockSchema.NestedBlocks, "locals",
			"%s block should support 'locals' nested block per spec", blockType)
	}
}

// TestBasicK8sObjectSchema verifies the basic K8s object schema
func TestBasicK8sObjectSchema(t *testing.T) {
	k8sObj := basicK8sObjectSchema()

	// Should have required apiVersion and kind
	assert.Contains(t, k8sObj.Attributes, "apiVersion")
	assert.Contains(t, k8sObj.Attributes, "kind")
	assert.Contains(t, k8sObj.Attributes, "metadata")

	apiVersionAttr := k8sObj.Attributes["apiVersion"]
	kindAttr := k8sObj.Attributes["kind"]

	assert.True(t, apiVersionAttr.IsRequired, "apiVersion should be required")
	assert.True(t, kindAttr.IsRequired, "kind should be required")

	// Metadata should be optional object
	metadataAttr := k8sObj.Attributes["metadata"]
	assert.True(t, metadataAttr.IsOptional, "metadata should be optional")

	// Metadata should have name, namespace, labels, annotations
	metadataObj, ok := metadataAttr.Constraint.(schema.Object)
	require.True(t, ok, "metadata should be an object")

	assert.Contains(t, metadataObj.Attributes, "name")
	assert.Contains(t, metadataObj.Attributes, "generateName")
	assert.Contains(t, metadataObj.Attributes, "namespace")
	assert.Contains(t, metadataObj.Attributes, "labels")
	assert.Contains(t, metadataObj.Attributes, "annotations")
}

// TestWithoutStatus verifies WithoutStatus removes status attribute
func TestWithoutStatus(t *testing.T) {
	tests := []struct {
		name             string
		input            *schema.AttributeSchema
		shouldHaveStatus bool
	}{
		{
			name:             "nil schema",
			input:            nil,
			shouldHaveStatus: false,
		},
		{
			name: "non-object constraint",
			input: &schema.AttributeSchema{
				Constraint: schema.String{},
			},
			shouldHaveStatus: false,
		},
		{
			name: "object without status",
			input: &schema.AttributeSchema{
				Constraint: schema.Object{
					Attributes: map[string]*schema.AttributeSchema{
						"spec": {IsOptional: true},
					},
				},
			},
			shouldHaveStatus: false,
		},
		{
			name: "object with status",
			input: &schema.AttributeSchema{
				Constraint: schema.Object{
					Attributes: map[string]*schema.AttributeSchema{
						"spec":   {IsOptional: true},
						"status": {IsOptional: true},
					},
				},
			},
			shouldHaveStatus: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := WithoutStatus(tt.input)

			if tt.input == nil {
				assert.Nil(t, result)
				return
			}

			if !tt.shouldHaveStatus {
				// Result should be same as input
				assert.Equal(t, tt.input, result)
				return
			}

			// Should have removed status
			obj, ok := result.Constraint.(schema.Object)
			require.True(t, ok)
			assert.NotContains(t, obj.Attributes, "status")
			assert.Contains(t, obj.Attributes, "spec")

			// Original should be unchanged
			origObj, _ := tt.input.Constraint.(schema.Object)
			assert.Contains(t, origObj.Attributes, "status")
		})
	}
}

// TestWithStatusOnly verifies WithStatusOnly keeps only status attribute
func TestWithStatusOnly(t *testing.T) {
	tests := []struct {
		name             string
		input            *schema.AttributeSchema
		shouldHaveStatus bool
	}{
		{
			name:             "nil schema",
			input:            nil,
			shouldHaveStatus: false,
		},
		{
			name: "non-object constraint",
			input: &schema.AttributeSchema{
				Constraint: schema.String{},
			},
			shouldHaveStatus: false,
		},
		{
			name: "object without status",
			input: &schema.AttributeSchema{
				Constraint: schema.Object{
					Attributes: map[string]*schema.AttributeSchema{
						"spec": {IsOptional: true},
					},
				},
			},
			shouldHaveStatus: false,
		},
		{
			name: "object with status and spec",
			input: &schema.AttributeSchema{
				Constraint: schema.Object{
					Attributes: map[string]*schema.AttributeSchema{
						"spec":   {IsOptional: true},
						"status": {IsOptional: true},
					},
				},
			},
			shouldHaveStatus: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := WithStatusOnly(tt.input)

			if tt.input == nil {
				assert.Nil(t, result)
				return
			}

			if !tt.shouldHaveStatus {
				// Result should be same as input
				assert.Equal(t, tt.input, result)
				return
			}

			// Should have only status
			obj, ok := result.Constraint.(schema.Object)
			require.True(t, ok)
			assert.Contains(t, obj.Attributes, "status")
			assert.NotContains(t, obj.Attributes, "spec")
			assert.Len(t, obj.Attributes, 1)

			// Original should be unchanged
			origObj, _ := tt.input.Constraint.(schema.Object)
			assert.Contains(t, origObj.Attributes, "status")
			assert.Contains(t, origObj.Attributes, "spec")
		})
	}
}

// TestWithoutAPIVersionAndKind verifies removal of apiVersion and kind
func TestWithoutAPIVersionAndKind(t *testing.T) {
	tests := []struct {
		name  string
		input *schema.AttributeSchema
		want  []string // attributes that should remain
	}{
		{
			name:  "nil schema",
			input: nil,
			want:  nil,
		},
		{
			name: "non-object constraint",
			input: &schema.AttributeSchema{
				Constraint: schema.String{},
			},
			want: []string{},
		},
		{
			name: "object with apiVersion, kind, and others",
			input: &schema.AttributeSchema{
				Constraint: schema.Object{
					Attributes: map[string]*schema.AttributeSchema{
						"apiVersion": {IsRequired: true},
						"kind":       {IsRequired: true},
						"spec":       {IsOptional: true},
						"metadata":   {IsOptional: true},
					},
				},
			},
			want: []string{"spec", "metadata"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := WithoutAPIVersionAndKind(tt.input)

			if tt.input == nil {
				assert.Nil(t, result)
				return
			}

			obj, ok := result.Constraint.(schema.Object)
			if !ok {
				assert.Equal(t, tt.input, result)
				return
			}

			assert.NotContains(t, obj.Attributes, "apiVersion")
			assert.NotContains(t, obj.Attributes, "kind")

			for _, attr := range tt.want {
				assert.Contains(t, obj.Attributes, attr)
			}
		})
	}
}

// TestBasicBodyAttributeSchema verifies basic body attribute schema
func TestBasicBodyAttributeSchema(t *testing.T) {
	bodyAttr := basicBodyAttributeSchema()

	assert.True(t, bodyAttr.IsRequired, "body should be required")

	obj, ok := bodyAttr.Constraint.(schema.Object)
	require.True(t, ok, "body constraint should be object")

	// Should have basic K8s object structure
	assert.Contains(t, obj.Attributes, "apiVersion")
	assert.Contains(t, obj.Attributes, "kind")
	assert.Contains(t, obj.Attributes, "metadata")
}

// TestDependentSchemaOrDefault verifies DependentSchemaOrDefault function
func TestDependentSchemaOrDefault(t *testing.T) {
	mockSchema := &schema.AttributeSchema{
		Constraint: schema.Object{
			Attributes: map[string]*schema.AttributeSchema{
				"spec": {IsOptional: true},
			},
		},
	}

	tests := []struct {
		name         string
		source       string
		dyn          DynamicLookup
		expectCustom bool
	}{
		{
			name: "returns custom schema when dependentSchema succeeds",
			source: `resource "test" {
				body = {
					apiVersion = "v1"
					kind = "Pod"
				}
			}`,
			dyn: &mockDynamicLookup{
				schemas: map[string]map[string]*schema.AttributeSchema{
					"v1": {"Pod": mockSchema},
				},
			},
			expectCustom: true,
		},
		{
			name: "returns default schema when no body attribute",
			source: `resource "test" {
			}`,
			dyn:          &mockDynamicLookup{},
			expectCustom: false,
		},
		{
			name: "returns default schema when body is list",
			source: `resource "test" {
				body = ["item1", "item2"]
			}`,
			dyn:          &mockDynamicLookup{},
			expectCustom: false,
		},
		{
			name: "returns default schema when missing apiVersion",
			source: `resource "test" {
				body = {
					kind = "Pod"
				}
			}`,
			dyn:          &mockDynamicLookup{},
			expectCustom: false,
		},
		{
			name: "returns default schema when missing kind",
			source: `resource "test" {
				body = {
					apiVersion = "v1"
				}
			}`,
			dyn:          &mockDynamicLookup{},
			expectCustom: false,
		},
		{
			name: "returns default schema when no matching schema in lookup",
			source: `resource "test" {
				body = {
					apiVersion = "v1"
					kind = "Unknown"
				}
			}`,
			dyn:          &mockDynamicLookup{},
			expectCustom: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			file, diags := hclsyntax.ParseConfig([]byte(tt.source), "test.hcl", hcl.InitialPos)
			require.False(t, diags.HasErrors(), "parse should succeed")

			var block *hclsyntax.Block
			for _, b := range file.Body.(*hclsyntax.Body).Blocks {
				if b.Type == "resource" {
					block = b
					break
				}
			}
			require.NotNil(t, block, "should find resource block")

			result := DependentSchemaOrDefault(tt.dyn, block)

			require.NotNil(t, result, "should always return a schema")

			if tt.expectCustom {
				// Should return the custom schema
				obj, ok := result.Constraint.(schema.Object)
				require.True(t, ok, "should be object constraint")
				assert.Contains(t, obj.Attributes, "spec", "should have custom schema attributes")
			} else {
				// Should return basicBodyAttributeSchema (default K8s object)
				obj, ok := result.Constraint.(schema.Object)
				require.True(t, ok, "should be object constraint")
				assert.Contains(t, obj.Attributes, "apiVersion", "should have basic K8s object schema")
				assert.Contains(t, obj.Attributes, "kind", "should have basic K8s object schema")
			}
		})
	}
}

// TestBasicK8sObjectConstraint verifies exported helper
func TestBasicK8sObjectConstraint(t *testing.T) {
	result := BasicK8sObjectConstraint()

	assert.Contains(t, result.Attributes, "apiVersion")
	assert.Contains(t, result.Attributes, "kind")
	assert.Contains(t, result.Attributes, "metadata")
}

// TestConditionAttributes verifies all blocks that should support conditions do
func TestConditionAttributes(t *testing.T) {
	// Per spec: these blocks support condition attribute
	blocksWithCondition := []string{
		"resource", "resources", "group", "requirement",
	}

	for _, blockType := range blocksWithCondition {
		t.Run(blockType, func(t *testing.T) {
			blockSchema := std[blockType]
			require.NotNil(t, blockSchema, "%s should have schema", blockType)

			assert.Contains(t, blockSchema.Attributes, "condition",
				"%s should support 'condition' attribute per spec", blockType)

			condAttr := blockSchema.Attributes["condition"]
			assert.True(t, condAttr.IsOptional,
				"condition should be optional in %s per spec", blockType)

			// Condition should be boolean
			assert.EqualValues(t, schema.Bool{}, condAttr.Constraint,
				"condition should be boolean per spec")
		})
	}
}

// TestFunctionSignatures verifies function signatures are complete
func TestFunctionSignatures(t *testing.T) {
	funcs := stdFunctions()

	// Sample some functions to ensure they have proper signatures
	tests := []struct {
		name        string
		paramCount  int
		hasVarParam bool
	}{
		{"abs", 1, false},
		{"base64encode", 1, false},
		{"can", 1, false},
		{"concat", 0, true}, // variadic
		{"format", 1, true}, // format string + variadic args
		{"try", 0, true},    // variadic
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			sig, ok := funcs[tt.name]
			require.True(t, ok, "function %s should exist", tt.name)

			assert.Len(t, sig.Params, tt.paramCount,
				"function %s should have %d params", tt.name, tt.paramCount)

			if tt.hasVarParam {
				assert.NotNil(t, sig.VarParam,
					"function %s should have variadic param", tt.name)
			} else {
				assert.Nil(t, sig.VarParam,
					"function %s should not have variadic param", tt.name)
			}

			assert.NotEmpty(t, sig.Description,
				"function %s should have description", tt.name)
		})
	}
}
